project:
  type: website

website:
  title: "NASA-TLX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: preproc_pavlovia.qmd
        text: Preprocess Pavlovia Banch
      - href: analysis_pavlovia.qmd
        text: Analysis Pavlovia Banch
      - href: toloka_explore.qmd
        text: Ya.Toloka Exploration
      - href: preproc_toloka.qmd
        text: Preprocess Toloka Banch
      - href: analysis_toloka.qmd
        text: Analysis Toloka Banch

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



