project:
  type: website

website:
  title: "NASA-TLX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: preprocess.qmd
        text: Preprocess
      - href: analysis.qmd
        text: Analysis
      - href: toloka_explore.qmd
        text: Ya.Toloka Explore

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



