project:
  type: website

website:
  title: "NASA-TLX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: preproc_pavlovia.qmd
        text: Preprocess First Banch
      - href: analysis_pavlovia.qmd
        text: Analysis First Banch
      #- href: toloka_explore.qmd
      #  text: Second Banch Exploration
      - href: preproc_toloka.qmd
        text: Preprocess Second Banch
      - href: analysis_toloka.qmd
        text: Analysis Second Banch
      - href: correlations.qmd
        text: Correlations

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



