
```{r cor-opts}
# knitr::opts_chunk$set(eval = FALSE)
```

## Packages

```{r pkgs-correlations}
library(tidyverse)
theme_set(theme_bw()) # set black and white theme
library(ggcorrplot)
```

```{r}
rm(list = ls())
```

## Sample Size

```{r}
r_ci <- function(r, se) {
  r_ = atanh(r)
  lower_ = r_ - 1.96 * se
  upper_ = r_ + 1.96 * se
  lower = tanh(lower_)
  upper = tanh(upper_)
  cover_zero = ifelse(sign(lower) == sign(upper), FALSE, TRUE)
  return(tibble(r = r,
              se = se,
              lower = lower,
              upper = upper,
              cover_zero = cover_zero))
}
```

```{r}
seq(.01, .2, by = .01) |> 
  map(r_ci, r = .27)
```

```{r}
r_n_se <- function(se) {
  return(tibble(se = se,
         n = (1 / se)^2 + 3))
}

r_n_se_lazy <- function(r, se) {
  return(tibble(r = r,
                se = se,
                n = ((1-r^2) / se^2) + 2))
}
```

```{r}
seq(.05, 0.14, by = .01) |> 
  map(r_n_se)
```

```{r}
seq(.05, 0.14, by = .01) |> 
  map(r_n_se_lazy, r = .27)
```

## Reading data

```{r}
nasatlx_pav <- read_csv("../preproc-data/nasatlx_raw_score_pav_data.csv")
nasatlx_tol_raw <- read_csv("../preproc-data/nasatlx_raw_score_tol_data.csv")
nasatlx_tol_weighted <- read_csv("../preproc-data/nasatlx_weighted_score_tol_data.csv") |> 
  rename_all(.funs = str_remove_all, pattern = "_w")
```

## Correlations First Banch

```{r}
nasatlx_pav |> 
  filter(task == "MR" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Mental Rotation Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "MR" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Mental Rotation Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "MR" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Mental Rotation Hard",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "MS" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Memory Span Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "MS" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Memory Span Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "MS" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Memory Span Hard",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "ST" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Sternberg Task Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "ST" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Sternberg Task Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_pav |> 
  filter(task == "ST" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "First Banch. Sternberg Task Hard",
             show.legend = FALSE)
```



## Correlations Second Banch

### Raw

```{r}
nasatlx_tol_raw |> 
  filter(task == "MR" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Mental Rotation Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "MR" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Mental Rotation Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "MR" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Mental Rotation Hard",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "MS" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Memory Span Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "MS" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Memory Span Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "MS" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Memory Span Hard",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "ST" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Sternberg Task Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw|> 
  filter(task == "ST" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Sternberg Task Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_raw |> 
  filter(task == "ST" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Raw. Sternberg Task Hard",
             show.legend = FALSE)
```


### Weighted

```{r}
nasatlx_tol_weighted |> 
  filter(task == "MR" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Mental Rotation Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "MR" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Mental Rotation Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "MR" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Mental Rotation Hard",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "MS" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Memory Span Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "MS" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Memory Span Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "MS" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Memory Span Hard",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "ST" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Sternberg Task Easy",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "ST" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Sternberg Task Medium",
             show.legend = FALSE)
```

```{r}
nasatlx_tol_weighted |> 
  filter(task == "ST" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Second Banch. Weighted. Sternberg Task Hard",
             show.legend = FALSE)
```


## Merger Fist and Second Banch Raw Score

```{r}
nasatlx_pav |> 
  bind_rows(nasatlx_tol_raw) |> 
  mutate(pool = ifelse(is.na(pool), "pool0", pool)) -> nasatlx_all
```

### MR Easy
```{r}
nasatlx_all |> 
  filter(task == "MR" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Mental Rotation Easy",
             show.legend = FALSE)
```

### MR Medium
```{r}
nasatlx_all |> 
  filter(task == "MR" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Mental Rotation Medium",
             show.legend = FALSE)
```

### MR Hard
```{r}
nasatlx_all |> 
  filter(task == "MR" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Mental Rotation Hard",
             show.legend = FALSE)
```

### MS Easy
```{r}
nasatlx_all |> 
  filter(task == "MS" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Memory Span Easy",
             show.legend = FALSE)
```

### MS Medium
```{r}
nasatlx_all |> 
  filter(task == "MS" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Memory Span Medium",
             show.legend = FALSE)
```

### MS Hard
```{r}
nasatlx_all |> 
  filter(task == "MS" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Memory Span Hard",
             show.legend = FALSE)
```

### ST Easy
```{r}
nasatlx_all |> 
  filter(task == "ST" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Sternberg Task Easy",
             show.legend = FALSE)
```

### ST Medium
```{r}
nasatlx_all |> 
  filter(task == "ST" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Sternberg Task Medium",
             show.legend = FALSE)
```

### ST Hard
```{r}
nasatlx_all |> 
  filter(task == "ST" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "All Data. Raw. Sternberg Task Hard",
             show.legend = FALSE)
```

### All tasks. All levels
```{r}
gridExtra::grid.arrange(
  nasatlx_all |> 
  filter(task == "MR" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "MR Easy",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "MR" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "MR Medium",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "MR" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "MR Hard",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "MS" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "MS Easy",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "MS" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "MS Medium",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "MS" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "MS Hard",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "ST" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "ST Easy",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "ST" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "ST Medium",
             show.legend = FALSE),
  nasatlx_all |> 
  filter(task == "ST" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR) |> 
  cor(use = "complete.obs") |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 2,
             colors = c("indianred1", "white", "royalblue1"),
             title = "ST Hard",
             show.legend = FALSE)
)
```

### Pooled Correlation Matrix

```{r}

nasatlx_all |> 
  filter(task == "MR" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> MR_easy_r_

nasatlx_all |> 
  filter(task == "MR" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> MR_medium_r_

nasatlx_all |> 
  filter(task == "MR" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> MR_hard_r_

nasatlx_all |> 
  filter(task == "MS" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> MS_easy_r_

nasatlx_all |> 
  filter(task == "MS" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> MS_medium_r_

nasatlx_all |> 
  filter(task == "MS" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> MS_hard_r_

nasatlx_all |> 
  filter(task == "ST" & level == "easy") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> ST_easy_r_

nasatlx_all |> 
  filter(task == "ST" & level == "medium") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> ST_medium_r_

nasatlx_all |> 
  filter(task == "ST" & level == "hard") |> 
  select(ME, PH, TI, PE, EF, FR, OW) |> 
  cor(use = "complete.obs") |> 
  atanh() -> ST_hard_r_
```

```{r}
((MR_easy_r_ + MR_medium_r_ + MR_hard_r_ + MS_easy_r_ + MS_medium_r_ + MS_hard_r_ + ST_easy_r_ + ST_medium_r_ + ST_hard_r_) / 9) |> tanh() -> pooled_matrix
```

```{r}
pooled_matrix |> 
  ggcorrplot(type = "lower", 
             lab = TRUE,
             lab_size = 3,
             colors = c("indianred1", "white", "royalblue1"),
             title = "Polled Matrix. Raw.",
             show.legend = FALSE)
```


