sink("data_files.txt")
print("DATA PAV")
dir("../data-pav")
print("")
print("")
print("")
print("DATA TOLOKA POOL 1")
dir("../data-toloka/pool1")
print("")
print("")
print("")
print("DATA TOLOKA POOL 2")
dir("../data-toloka/pool2")
print("")
print("")
print("")
print("DATA TOLOKA POOL 34")
dir("../data-toloka/pool34")
print("")
sink()
